### ISSUE TITLE
`Ints.checkedCast` vs. `Math.toIntExact`

### ISSUE THREAD

**Issue by Stephan202** [gaul/modernizer-maven-plugin#102]
Guava's [`Ints.checkedCast`](https://google.github.io/guava/releases/28.1-jre/api/docs/com/google/common/primitives/Ints.html#checkedCast-long-) can be replaced with Java 8's [`Math.toIntExact`](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#toIntExact-long-). As described in google/guava#3105, the only difference is the exception they throw. Keeping in mind this subtle difference: is `Ints.checkedCast` eligible for inclusion in `modernizer-maven-plugin`? If so, I'll open a PR.

**Comment by gaul** [comment]
Modernizer should recommend this.  The violation comment could suggest catching `ArithmeticException`.  I also like https://github.com/google/guava/issues/3105#issuecomment-390493543 suggesting `Math.subtractExact` instead of `IntMath.checkedSubtract`.

**Comment by Stephan202** [comment]
Alright, I filed #103.
