### ISSUE TITLE
Upgrade ASM for jdk 14 / 15 support to ASM 7.3.1

### ISSUE THREAD

**Issue by hazendaz** [gaul/modernizer-maven-plugin#105]
Direct support for jdk 14 / 15 fails due to old ASM.  Please upgrade.  See ASM notes https://asm.ow2.io/versions.html.

Overriding this project for ASM 7.3.1 currently fixes the issue.

**Comment by gaul** [comment]
Can you submit a pull request?

**Comment by hazendaz** [comment]
@gaul Certainly!  I just forked the repo.  I'll start work on this and get it over once all tests are confirmed.  Thanks.

**Comment by gaul** [comment]
Fixed by 8269ed8cce6df6b84756242708c74a3ba2ee9864.
