### ISSUE TITLE
Figure out minimum supported Java version

### ISSUE THREAD

**Issue by gaul** [gaul/modernizer-maven-plugin#110]
I have previously tested modernizer with Java 6 although various Java 7 dependencies have crept in since CI does not enforce this.  I believe that applications can still run modernizer with Java 6 although developers cannot compile and test with it due to #109, Guava, and probably other things.  I don't know that this project needs any sort of heroics but if earlier JDK support is easy then it would be nice to have.  At a minimum JDK 8 should work since this is LTS and hopefully JDK 7 too.

cc: @hazendaz

**Comment by gaul** [comment]
Strangely Travis uses openjdk8 when setting `dist: trusty` and `java: openjdk7`:

https://travis-ci.org/gaul/modernizer-maven-plugin

**Comment by hazendaz** [comment]
Travis is using ubuntu.  Trusty is the old one.  It's not a good idea to go back to that.  Xenial is the current main used one.  With oracle changing licensing terms, you won't find anything but openjdk getting used now.  This has to do with a script that was written some time ago that allowed to override travis to pull whatever up next jdks.  That was consumed into travis itself.  So the new builds will ship with whatever jdk was allowed (most likely 11).  But most projects will request variuos others.  Those others, only allow 8 and above currently.

**Comment by hazendaz** [comment]
See https://docs.travis-ci.com/user/reference/overview/

**Comment by hazendaz** [comment]
Linux #

A sudo enabled, full virtual machine per build, that runs Linux, one of:

    Ubuntu Bionic 18.04
    Ubuntu Xenial 16.04 default
    Ubuntu Trusty 14.04
    Ubuntu Precise 12.04

**Comment by hazendaz** [comment]
Precise still allows jdk 6 but will eventualy go away.  Trusty was the main one used until middle to end of last year when they started rolling out randomly everyone to xenial.

**Comment by hazendaz** [comment]
This is helpful too -> https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

**Comment by gaul** [comment]
Sorry I pushed the wrong branch.  Several of the tests require Java 8 to complete:

https://travis-ci.org/gaul/modernizer-maven-plugin/builds/645953599

Thus I think that CI should continue testing with JDK 8 and pom.xml continue to target JDK 6 until this becomes more irritating.
