### ISSUE TITLE
Use public scope on your classes

### ISSUE THREAD

**Issue by brianhks** [gaul/modernizer-maven-plugin#111]
The way you have designed your Modernizer code it can be easily used outside of a maven plugin except that the classes are not public.  I see no benefit of keeping the classes package private.  However if they were public I could wrap it in a command line utility or incorporate it into other build tools.

**Comment by gaul** [comment]
I originally kept the interfaces private so that the API could evolve but I doubt the interfaces will change much any more.  Could you submit a pull request with the APIs you want made public?

**Comment by brianhks** [comment]
Yes, will do.

**Comment by gaul** [comment]
@brianhks I would like to run another release soon.  Do you plan to work on this in the near-term?

**Comment by brianhks** [comment]
Oh yes sorry I have a pull request I'll get it to you today.

**Comment by brianhks** [comment]
I created pull request https://github.com/gaul/modernizer-maven-plugin/pull/113
