### ISSUE TITLE
No worky on java 14

### ISSUE THREAD

**Issue by davidkarlsen** [gaul/modernizer-maven-plugin#112]
Even with https://github.com/gaul/modernizer-maven-plugin/commit/8269ed8cce6df6b84756242708c74a3ba2ee9864 and running on 2.0.0 I get
```
[ERROR] Failed to execute goal org.gaul:modernizer-maven-plugin:2.0.0:modernizer (modernizer) on project jfr-srv-openapi: Execution modernizer of goal org.gaul:modernizer-maven-plugin:2.0.0:modernizer failed: Unsupported class file major version 58 -> [Help 1]
```

**Comment by davidkarlsen** [comment]
Ah - I see it has not been released yet - could you push out a release please?

**Comment by gaul** [comment]
I just pushed a new 2.1.0-SNAPSHOT.  Can you verify that this addresses your symptoms?  I will run a new release soon.

**Comment by davidkarlsen** [comment]
It passed with 2.0.1-SNAPSHOT yesterday.

**Comment by gaul** [comment]
Deployed 2.1.0.
