### ISSUE TITLE
Classes annotated with javax.annotation.Generated and javax.annotation.processing.Generated are not ignored

### ISSUE THREAD

**Issue by nickstolwijk** [gaul/modernizer-maven-plugin#117]
Expected behaviour:
Modernizer does not trigger on generated classes.

Shown behaviour:
Modernizer does trigger on classes with @Generated.

The current implementation looks at the class file to find the annotations. The default annotations (javax.annotation.Generated and javax.annotation.processing.Generated) are #RetentionLevel(SOURCE) and thus not available after compilation.

**Comment by gaul** [comment]
I don't think that modernizer can do anything about this since these external classes use those retention levels.  However if you annotate with another class with the name "Generated" and the correct retention level then it should work.  Otherwise you need to write some exclusions.

**Comment by nickstolwijk** [comment]
Unfortunately, I can't control the generator. :-( I have for now added an exclusion.
