### ISSUE TITLE
Crash on Java 15 preview-features

### ISSUE THREAD

**Issue by nickstolwijk** [gaul/modernizer-maven-plugin#118]
I was playing around with the Java 15 preview features (records to be exact) and Modernizer crashed on my code.

I could fix it by upgrade ASM to 8 and enable ASM8. I see that there is also an ASM9. What is your policy on updating ASM? The latest and greatest or the one for the latest release (including preview-features?) of the JDK?

**Comment by gaul** [comment]
This is probably fine to upgrade to the latest ASM.  However I notice that Modernizer does not document its backward compatibility with older Java versions.  Could you research this and document it?

**Comment by nickstolwijk** [comment]
> However I notice that Modernizer does not document its backward compatibility

I think you mean ASM? I will have a look if I can find anything.

**Comment by nickstolwijk** [comment]
They compile their code with Java 8, but use ASM to retrofit their own code to make it bytecode compitable with Java 1.5. [1]

[1] https://gitlab.ow2.org/asm/asm/-/blob/master/tools/retrofitter/src/main/java/org/objectweb/asm/tools/Retrofitter.java

**Comment by nickstolwijk** [comment]
Created PR #119  to solve this issue.

**Comment by gaul** [comment]
Thanks for researching this!  It is good to know ASM isn't the limiting factor and I believe that at least JDK 6 and onward should work.  I encountered some problems building locally.  The winning combination ended up being:

```
JAVA_HOME=$HOME/bin/jdk1.8.0_162/ $HOME/bin/apache-maven-3.2.5/bin/mvn clean verify
```

**Comment by nickstolwijk** [comment]
I can build it with adopt-openjdk-11.0.9.1 and Maven 3.6.3.
