### ISSUE TITLE
2.2.0 release

### ISSUE THREAD

**Issue by gaul** [gaul/modernizer-maven-plugin#120]
Mostly to incorporate #119.

**Comment by nickstolwijk** [comment]
Java 16 just got to GA, but unfortunately Modernizer 2.1.0 doesn't support this GA release yet. Are there any obstacles to releasing 2.2.0?

**Comment by gaul** [comment]
Done:

https://github.com/gaul/modernizer-maven-plugin/releases/tag/modernizer-maven-plugin-2.2.0
