### ISSUE TITLE
Several project dependencies are outdated

### ISSUE THREAD

**Issue by binkley** [gaul/modernizer-maven-plugin#131]
I ran into an issue with CVE dependency scanning for Gradle counterpart to this plugin which depends on this project.

Transitively, there is a dependency here on a crufty version of `plexus-utils` that has an XML injection security bug.  I filled against the Gradle plugin project here:

https://github.com/andygoossens/gradle-modernizer-plugin/issues/1

Reviewing `pom.xml` for the plugin, I see many or most dependencies our outdated.  A refresh to latest or near latest versions would likely address the CVE, as well as pick up any dependency bug fixes that have happened along the way.  It's not sexy work, but is good craftsmanship.

When I gain some roundtuits, I may try updating myself, and see how it goes.

**Comment by gaul** [comment]
I can't process an issue that boils down to, "old versions, lolz!".  If you have something specific you want to fix please submit a PR.  Note that several versions are pinned due to supporting older Java versions.
