### ISSUE TITLE
Simple concatenations should not be flagged

### ISSUE THREAD

**Issue by yeikel** [gaul/modernizer-maven-plugin#140]
Starting with 2.4.0, I received the following error: `Prefer java.lang.String.join or use java.util.stream.Stream with java.util.stream.Collectors.joining`

While it is true that in loops, it is generally advised to do that, there is nothing wrong with simple concatenations such as a+b

In fact, they may perform better than the alternatives in newer java versions

Source : https://www.youtube.com/watch?v=w56RUzBLaRE

See : https://openjdk.java.net/jeps/280

Offending code : 

`final String result = "$." + StringUtils.join(outputKeys, ".");
`

One way to fix it(as per the warning) is to  : 

`final String result = String.join("","$.",StringUtils.join(outputKeys, "."));`

But that is hardly better than the previous code

**Comment by yeikel** [comment]
Never mind, the warning is just not clear. This seems to be related to https://github.com/gaul/modernizer-maven-plugin/commit/688d9aa83151a561e807097b1078205ccbe94043

**Comment by gaul** [comment]
What would make this better?  Could we add column information?  Is this technically possible?

**Comment by yeikel** [comment]
I think that simply adding the banned api to the error messages would clarify them

I was able to find what the error meant when I checked the rules definition

**Comment by gaul** [comment]
Pull requests welcome!
