### ISSUE TITLE
why prefer `StringBuilder` instead of `StringBuffer`?

### ISSUE THREAD

**Issue by youzipi** [gaul/modernizer-maven-plugin#149]
`StringBuilder` and `StringBuffer` provides different concurrency guarantees.
I do not see any filter that detects if the code is in an concurrency scenarios.
IMO, we have no way to achieve this.
so, why we need this modernizer rule?

**Comment by gaul** [comment]
Most people don't need the concurrency guarantee and don't even realize the overhead, similar to `Vector`.  You can use `synchronized (stringBuffer)` if you need this.
