### ISSUE TITLE
Way to extract modernizer logs / reports

### ISSUE THREAD

**Issue by abhisheksurve45** [gaul/modernizer-maven-plugin#158]
Hi

Was wondering if there's any way to extract the modernizer comments/reports.

Right now we are using grep.

Example Logs on executing maven compile

```
11:56:02 [ERROR] /home/project/src/main/java/com/test/project/package/SomeClass.java:102: Prefer Stream.skip(position).findFirst().orElse(defaultValue)
```

**Comment by gaul** [comment]
Modernizer could add a new goal which dumps an XML machine-readable report.  This is easy to add, just change `ModernizerMojo.emitViolation`.  Would you like to submit a PR?
