### ISSUE TITLE
Optional.get() as optional violation

### ISSUE THREAD

**Issue by rovarga** [gaul/modernizer-maven-plugin#159]
Java 10+ [Optional.orElseThrow()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#orElseThrow()) provides much more meaningful name to the same as Optional.get(). The benefit is implied semantics message and disambiguation from Future.get() -- which is a clear visual clue.

While it is possible to add this violation via config, it would be nicer if these sorts of recommendations were readily-available through a config option -- perhaps \<betterAlternative>true\</betterAlternative>?

**Comment by gaul** [comment]
Duplicate of #147?

**Comment by rovarga** [comment]
Ah, yes, sorry.
