### ISSUE TITLE
Violation not being detected 

### ISSUE THREAD

**Issue by pmverma** [gaul/modernizer-maven-plugin#176]
With the following in a source file, it is detected.
```
        Charset utf8 = Charsets.UTF_8;
```
But not with
```
        String utf8String = Charsets.UTF_8.name();
```

**Comment by gaul** [comment]
Could you be more specific about your symptoms?  When I change `ModernizerTest.CharsetsTestClass` to call `name()` it correctly flags the violation.

**Comment by pmverma** [comment]
I was expecting my maven build to fail but it didn’t fail with `Charsets.UTF_8.name()`.

**Comment by gaul** [comment]
Please provide a unit test that fails via a PR.  My previous comment suggests that this works correctly today.  It sounds like you have some configuration error where modernizer is not running.

**Comment by pmverma** [comment]
Oh, it's my fault. I was binding with the `validate` phase which won't work because modernize works on compiled class.
