### ISSUE TITLE
Release a new version to support Java 20

### ISSUE THREAD

**Issue by Harmelodic** [gaul/modernizer-maven-plugin#177]
As of the merging of this PR on the 22nd November 2022, `modernizer-maven-plugin` should be able to support Java 20:
- https://github.com/gaul/modernizer-maven-plugin/pull/154

However, the latest `modernizer-maven-plugin` release was `2.5.0` on the November 13th 2022 (i.e. before the Java 20 PR)

Now that [Java 20 is released](https://jdk.java.net/20/), it would be great to get a new release of `modernizer-maven-plugin` to receive that Java 20 support.

**Comment by gaul** [comment]
Tagged and deployed.  Thanks for the reminder.
