### ISSUE TITLE
JDK 21 compatibility

### ISSUE THREAD

**Issue by wendigo** [gaul/modernizer-maven-plugin#192]
Version 2.6.0 fails when reading JDK 21 class files.

```
Execution modernizer of goal org.gaul:modernizer-maven-plugin:2.6.0:modernizer failed: Unsupported class file major version 65
```

**Comment by gaul** [comment]
Probably need to upgrade asm:

https://asm.ow2.io/versions.html

Can you test this and submit a PR?
