### ISSUE TITLE
Is 2.7.0-SNAPSHOT published somewhere?

### ISSUE THREAD

**Issue by ilgrosso** [gaul/modernizer-maven-plugin#211]
I need JDK 21 compatibility #192 in one of my projects but I cannot find where 2.7.0-SNAPSHOT is published.

Thank you.

**Comment by gaul** [comment]
Deployed.  Please test and report back.

**Comment by ilgrosso** [comment]
Thank you @gaul I was able to download 2.7.0-SNAPSHOT.
