### ISSUE TITLE
Unsupported class file major version 65

### ISSUE THREAD

**Issue by talios** [gaul/modernizer-maven-plugin#212]
Looks like modernizer doesn't like running under the newly released JDK 21 (ok sure, it only just came out yesterday).

**Comment by gaul** [comment]
Does 2.6.0-SNAPSHOT resolve your symptoms?  If so I can run a new release.

**Comment by mnoteberg-non** [comment]
We're unable to test with snapshot versions of the plugin, but we solved "Unsupported class file major version 65" by overriding the asm version used by the plugin to 9.5.

That change already seems to be merged into master here: https://github.com/gaul/modernizer-maven-plugin/pull/198 so please just release a new version of the plugin 🙏
