### ISSUE TITLE
FYI: Apache Maven core plugins are going for 3.6.3 as prerequisite

### ISSUE THREAD

**Issue by cstamas** [gaul/modernizer-maven-plugin#259]
Just FYI, as latest dependabot PRs for latest Maven Core plugins fail due being built with _ancient_ Maven 3.2.5.
Do you really _need_ to cover history of 10+ years?

Apache Maven project decided to lift up all the core plugins prerequisite to Maven 3.6.3 (same for Codehaus Mojos).

**Comment by gaul** [comment]
For 2.9.0 let's just revert so we get a known good package.  For the next 3.0.0 can you submit a PR that brings Modernizer into the same dependencies as other Maven core plugins?  It would be good if we could document the requirements in README.md.

**Comment by cstamas** [comment]
Will prep a PR

**Comment by gaul** [comment]
Fixed by 1616064ba43103636b8c7901b87ffff6f4e3bc1a.
