### ISSUE TITLE
Q: How do you release?

### ISSUE THREAD

**Issue by cstamas** [gaul/modernizer-maven-plugin#261]
Asking, as https://github.com/gaul/modernizer-maven-plugin/blob/8ddb06e85d9aa4cdb45504f937d6d4f9ec15d57d/pom.xml#L13 (current master!) still shows version 2.9.0! This means if anyone rebuilds locally, will _replace the release downloaded from Maven Central_.

**Comment by gaul** [comment]
Looks like I missed a step!  I manually run these commands for every release:

```sh
git rebase upstream/master
mvn versions:set -DnewVersion=1.2.2
git add -p
git commit -m 'modernizer-maven-plugin 1.2.2 release'
\mvn clean deploy -P release
git tag -a modernizer-maven-plugin-1.2.2 -m 'modernizer-maven-plugin 1.2.2 release'
mvn versions:set -DnewVersion=1.3.0-SNAPSHOT
git add -p
git commit -m 'Bump to 1.3.0-SNAPSHOT'
git push upstream master
git push upstream --tags
```

I haven't changed this process in 10 years -- is there a better way?

**Comment by gaul** [comment]
@cstamas any other cleanups we could make here?  I would like to make a new release soon.

**Comment by cstamas** [comment]
Nope, all looks good, thanks! Parent and staging plugin are gone, that was my goal.

**Comment by gaul** [comment]
Thanks!  Please open other issues if you spot potential improvements.
