### ISSUE TITLE
Java 24 support

### ISSUE THREAD

**Issue by yeikel** [gaul/modernizer-maven-plugin#286]
While  I understand that Java 24 is still in early access, I am logging it for awareness for now

Sample error:

```
Execution modernizer of goal org.gaul:modernizer-maven-plugin:2.9.0:modernizer failed: Unsupported class file major version 68

```

**Comment by gaul** [comment]
modernizer depends on [https://asm.ow2.io/](asm) for bytecode introspection.  So I guess we need to wait for its next release.

**Comment by yeikel** [comment]
> modernizer depends on [asm](https://asm.ow2.io/) for bytecode introspection. So I guess we need to wait for its next release.

Fair enough, let's keep this open until we can re-test with the newer ASM version
