### ISSUE TITLE
disable Modernizer via @SuppressWarnings annotation

### ISSUE THREAD

**Issue by gaul** [gaul/modernizer-maven-plugin#3]
@SuppressWarnings allows finer-grained suppression of violations than the existing file-based mechanism.

**Comment by ankon** [comment]
If I understand modernizer correctly, this wouldn't work: @SuppressWarnings is only retained in the source, not in the generated class files.

**Comment by andrewgaul** [comment]
@ankon I have limited background in annotation processing but I believe one can use the `RUNTIME` retention policy:

http://docs.oracle.com/javase/7/docs/api/java/lang/annotation/RetentionPolicy.html

**Comment by Stephan202** [comment]
@andrewgaul, that's true when one has control over the annotation. In this case, however, `java.lang.SuppressWarnings` is annotated `@Retention(RetentionPolicy.SOURCE)`. Not much we can do about that :/

**Comment by andrewgaul** [comment]
I see, so we would need a new `SuppressModernizerWarnings` class with the `RUNTIME` policy?

**Comment by Stephan202** [comment]
That would be a solution, yes. (Though not quite as nice as the original suggestion.) Have no better idea at this point. (Other than adding support for source code analysis to the plugin, of course!)

**Comment by petteyg** [comment]
asm is operating on the bytecode, so I would think RententionPolicy.CLASS should be sufficient.

**Comment by Stephan202** [comment]
Ah, right. That's more appropriate indeed.

**Comment by ankon** [comment]
Thinking a bit outside of the box here: One "evil" way could be to add a annotation processing step, which finds the @SuppressWarnings that pertain to modernizer, and dumps those into an exclusion file which is then used by the actual modernizer goal.

This would avoid polluting sources with build-system specific things ... except that of course the value in the annotation is also modernizer-specific, and in fact eclipse warns about unrecognized values in it :/

**Comment by vorburger** [comment]
> way could be to add a annotation processing step, which finds the @SuppressWarnings that pertain to modernizer, and dumps those into an exclusion file which is then used by the actual modernizer goal.

This would be cool, and help with https://github.com/gaul/modernizer-maven-plugin/issues/28 as well...

**Comment by keith-turner** [comment]
Findbugs has its own annotation for suppressing warnings.  One interesting thing finbugs did is not caring which package the annotation is in, see : https://stackoverflow.com/a/44947252 .  This allows users to declare the annotation and avoid having a dependency on findbugs.

**Comment by jhaber** [comment]
Just a heads up we're going to be working on this in our fork (https://github.com/HubSpot/modernizer-maven-plugin) and will upstream the changes once they're ready.

**Comment by gaul** [comment]
@jhaber Any updates on this?

**Comment by jhaber** [comment]
We have it working where you can put `@SuppressWarnings("modernizer")` at the class level and that will get respected, and there is a PR to support this at the method level: https://github.com/HubSpot/modernizer-maven-plugin/pull/2

Once that is merged, we were thinking that it would be a good MVP of this feature and we would send a PR to upstream those changes. 

Some notes about our approach: 
- it depends on an annotation processor, which means that users need to add a new dependency for these suppressions to work (using `<scope>provided</scope>` on this dependency is fine)
- the annotation processor writes a CSV containing information about the excluded classes/methods which the plugin reads. We weren't sure if you had a preference for using something more structured like XML/JSON/YAML (the latter two would require additional dependencies in the processor/plugin)
- `@SuppressWarnings("modernizer")` will disable all modernizer checks for the relevant code block. To support more granular suppressions, we would probably need to expand the violations file schema to include support for specifying an identifier for each violation. For example, the `com/google/common/base/Function` violation could have `<id>GuavaFunction</id>` and then you could do `@SuppressWarnings("modernizer:GuavaFunction")` to only suppress that specific check (this matches the syntax that other tools like checkstyle use to suppress specific checks, [for example](https://github.com/apache/maven-shared/blob/28046c02f72245d39bc2b873cc53745dc4ce872a/maven-shared-utils/src/main/java/org/apache/maven/shared/utils/reflection/Reflector.java#L446))

**Comment by gaul** [comment]
Sounds good.  I have concerns about the large number of spurious changes in that pull request so please minimize the noise before submitting a pull request.  I look forward to this feature!
