### ISSUE TITLE
Generate plugin docs and publish to github.io pages

### ISSUE THREAD

**Issue by ctubbsii** [gaul/modernizer-maven-plugin#47]

**Comment by gaul** [comment]
Is there some low-effort, repeatable way to do this, perhaps via a Maven plugin?

**Comment by ctubbsii** [comment]
@gual Yeah, the [maven-site-plugin] generates static websites for maven projects. It can be tweaked with various reporting plugins. The [maven-plugin-plugin] is a particularly useful reporting plugin for generating sites for maven plugins. Once configured, you can generate the site with the built-in [site lifecycle] `mvn site`.

You can manually copy the generated static site's html from `target/` to a `gh-pages` branch in the project. If the repository is properly configured in GitHub, that would cause the generated docs to be hosted at https://gaul.github.io/modernizer-maven-plugin/ (see https://pages.github.com/ for info on static site hosting on GitHub).

Instead of manually copying, publishing can be automated further by binding plugins to `deploy` phase of the site lifecycle so they automatically publish when you do `mvn site-deploy`. Several projects I host at https://github.com/revelc do this, if you want to see some example `pom.xml` files:

* [formatter-maven-plugin] currently uses [wagon-git] and [wagon-ssh] to publish
* (my preferred method): [apilyzer-maven-plugin], [zookeeper-maven-plugin] and others skip the built-in `deploy` action of [maven-site-plugin] and instead use GitHub's own [site-maven-plugin], which uses GitHub's API to directly upload the site to the `gh-pages` branch in the repository.

[site lifecycle]: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Built-in_Lifecycle_Bindings
[maven-site-plugin]: https://maven.apache.org/plugins/maven-site-plugin/
[maven-plugin-plugin]: https://maven.apache.org/plugin-tools/maven-plugin-plugin/
[formatter-maven-plugin]: https://github.com/revelc/formatter-maven-plugin/
[wagon-git]: https://github.com/trajano/wagon-git
[wagon-ssh]: https://maven.apache.org/wagon/wagon-providers/wagon-ssh/
[apilyzer-maven-plugin]: https://github.com/revelc/apilyzer-maven-plugin/
[zookeeper-maven-plugin]: https://github.com/revelc/zookeeper-maven-plugin/
[site-maven-plugin]: https://github.com/github/maven-plugins

**Comment by mprins** [comment]
I use the `maven-site-plugin` to generate the site and `maven-scm-publish-plugin` to publish to a `gh-pages` branch; I've found this to be the most reliable way, also for very large, multimodule sites.

As an example see https://github.com/GeoDienstenCentrum/schemaspy-maven-plugin/blob/master/pom.xml 

I can get you started with a PR if you like

**Comment by gaul** [comment]
@mprins I would appreciate a PR!  @ctubbsii gave some good background but I don't have the cycles to look into this myself.

**Comment by mprins** [comment]
So I've created the PR about 2 months ago, but so far no reaction
