### ISSUE TITLE
Option to ignore/exclude by class name

### ISSUE THREAD

**Issue by vorburger** [gaul/modernizer-maven-plugin#64]
It would be useful to be able to ignore/exclude by class name reg exp, e.g. for some cases of https://github.com/gaul/modernizer-maven-plugin/issues/28.

This is not possible today; the `exclusionPatterns` actually do not match on class name, but on _tokens_ (I just debug it...), and the `ignorePackages` only on package names.

I'll see if I can come up with a PR for an `ignoreClassPatterns` kind of thing.

**Comment by gaul** [comment]
This makes sense although I share your confusion now that there are so many ways to exclude code.

**Comment by vorburger** [comment]
closing this, now that https://github.com/gaul/modernizer-maven-plugin/pull/67 is merged; thanks again @gaul !
