### ISSUE TITLE
Release of 1.7.0 to Maven central

### ISSUE THREAD

**Issue by vorburger** [gaul/modernizer-maven-plugin#69]
just a placeholder issue that I can get notified whenever @gaul you'll have a chance to release 1.7.0 ...

see also https://github.com/gaul/modernizer-maven-plugin/pull/67

Thank you!

**Comment by gaul** [comment]
I would like to support Java 10 in the next version.  We will need to upgrade ASM to 6.1, which is currently in beta.

**Comment by gaul** [comment]
Looks like ASM 6.1 will release around 20 March 2018, one week after JDK 10 releases:

https://mail.ow2.org/wws/arc/asm/2018-02/msg00012.html

**Comment by gaul** [comment]
Waiting on asm 7.0 final and for #74 to merge.

**Comment by vorburger** [comment]
@gaul thanks for the release! (We'll use it in https://git.opendaylight.org/gerrit/#/c/67838/)
