### ISSUE TITLE
JDK 10 immutable collection copy violations

### ISSUE THREAD

**Issue by gaul** [gaul/modernizer-maven-plugin#70]
JDK 10 will add `List.copyOf` and `Map.copyOf` which should replace Guava `ImmutableList.copyOf` and `ImmutableMap.copyOf`:

https://bugs.openjdk.java.net/browse/JDK-8177290

@vorburger Could you investigate this?

**Comment by Stephan202** [comment]
Hmm, the Guava team [sees that differently](https://github.com/google/guava/issues/2969#issuecomment-343989695). As a user I'm inclined to agree.

**Comment by gaul** [comment]
I disagree with their reasoning; especially exposing concrete Guava types in any public interface.  The Immutable* `@Deprecated` trick is cute, but I have used the concrete types in previous projects without any benefit.  In any case, Modernizer already recommends the Java 9 `List.of` and `Map.of` and this issue tracks the Java 10 additions.  I prefer to add these violations and users can disable them if they prefer the deprecated warnings.

**Comment by vorburger** [comment]
> @vorburger Could you investigate this?

@gaul thanks for pinging me; just FYI I'm unlikely to have the time to make new code contributions to this project in the short term, especially until I can actually use it (waiting for https://github.com/gaul/modernizer-maven-plugin/issues/69), but even then Java 10 related work would be a low prio; the environment where I'm using this is still on Java 8... ;-)

Having said above just to clarify expectations, my personal view on this particular question would be more with @Stephan202 and Guava's PoV - I have actually used `ImmutableList` and `ImmutableMap` a few times in APIs, to signal immutability to users. Of course is doesn't really prevent anyone from invoking its `@deprecated` methods like `add()` etc. but I still found using them as return type to clarify the intention. 

What would be really cool in a theoretical ideal world I guess would be some quality check tooling that would fail on use of mutator methods on immutable collection types. (Or, in Java v127, new immutable parent types without mutator methods; is that anywhere on the roadmap, anyone knows?)

But I respect that above may not be a generally widely accepted view, so I think it's not a problem if you want to add this to Modernizer, and then let users opt-out of this particular rule by disabling it.

**Comment by electrum** [comment]
One important difference for JDK immutable `Set` and `Map` is that the iteration order is unspecified, whereas the Guava versions preserve order.
