### ISSUE TITLE
"java.version" to Runtime.version()

### ISSUE THREAD

**Issue by mattnelson** [gaul/modernizer-maven-plugin#79]
[Runtime.version](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runtime.html#version()) was added in 9. Is it possible for modernizer to recognize this update flow?

```java
System.getProperty("java.version")
Runtime.version().major()
```

```
jshell
|  Welcome to JShell -- Version 11
|  For an introduction type: /help intro

jshell> System.getProperty("java.version")
$1 ==> "11"

jshell> Runtime.version().major();
$2 ==> 11
```

**Comment by gaul** [comment]
The current violation mechanism uses only method signatures, e.g., `System.getProperty`, and not their arguments.  We could special-case this with code if you want to submit a pull request.  I wonder what other methods have arguments like this?

**Comment by gaul** [comment]
Seems outside the scope of modernizer.
