### ISSUE TITLE
Don't check modernizer.javaVersion when execution is skipped

### ISSUE THREAD

**Issue by Serranya** [gaul/modernizer-maven-plugin#83]
When the execution of this plugin is skipped the plugin should not complain that the javaVersion is not specified.

**Comment by gaul** [comment]
I believe that `javaVersion` should not be required in `ModernizerMojo.java.`  Instead it `execute` should make sure this is set after the skip check.  Could you test this and submit a pull request if this works?

**Comment by Serranya** [comment]
Yeah
