### ISSUE TITLE
 Allow Matcher.appendReplacement for StringBuffer in JDK <= 8.

### ISSUE THREAD

**Issue by Dichotomia** [gaul/modernizer-maven-plugin#91]
Allow Matcher.appendReplacement for StringBuffer in JDK <= 8.

The API for Matcher.appendReplacement for StringBuilder has been added in JDK 9.

**Comment by gaul** [comment]
This sounds reasonable; could you submit a pull request?

**Comment by Dichotomia** [comment]
I did not study how this plugin work. Is there any way to exclude a violation based on his usage?

**Comment by gaul** [comment]
The README suggests a mechanism to do this:

https://github.com/gaul/modernizer-maven-plugin#ignoring-elements

**Comment by Dichotomia** [comment]
Yes i did this.

I was suggesting to modify the plugin because it is a general case.

Sorry for my English.

**Comment by gaul** [comment]
Adding new violations is easy; modify this XML file:

https://github.com/gaul/modernizer-maven-plugin/blob/master/modernizer-maven-plugin/src/main/resources/modernizer.xml

and submit a pull request!

**Comment by Dichotomia** [comment]
The problem is that rule is blocking me :

  <violation>
    <name>java/lang/StringBuffer."&lt;init&gt;":()V</name>
    <version>1.5</version>
    <comment>Prefer java.lang.StringBuilder</comment>
</violation>

The usage of StringBuilder is 

https://docs.oracle.com/javase/8/docs/api/java/util/regex/Matcher.html#appendReplacement-java.lang.StringBuffer-java.lang.String-

**Comment by gaul** [comment]
Sorry, I misunderstood your initial question.  I believe your source code has code like:

```java
StringBuffer sb = new StringBuffer();
...
matcher.appendReplacement​(sb, "someString");
```

modernizer suggests that you use `StringBuilder` which is unsynchronized.  Can you change your code?  If not please use the `@SuppressModernizer` annotation suggested above.

**Comment by Dichotomia** [comment]
Yes that is what the code looks like.

Ok for the moment i don't understand what the code do. Then i use the @SuppressModernizer annotation.

Thanks for the answer.

**Comment by Dichotomia** [comment]
Maybe we will wait java 9 for 

https://docs.oracle.com/javase/9/docs/api/java/util/regex/Matcher.html#appendReplacement-java.lang.StringBuilder-java.lang.String-

**Comment by gaul** [comment]
Ah, I understand the problem -- Java 1.5 introduced `StringBuilder` but Java 9 introduces `Matcher.appendReplacement(StringBuilder)`.  Unfortunately modernizer cannot detect this kind of situation and this is exactly the situation the suppression mechanism is designed for.  If you cannot use the suppression annotation you can work around this via the exclusion mechanism although you should prefer the former.
