### ISSUE TITLE
Add Automatic-Module-Name to annotations

### ISSUE THREAD

**Issue by rovarga** [gaul/modernizer-maven-plugin#93]
Since the annotations module does not commit to a JPMS module name, one cannot use it with in artifacts which want to be full JMPS modules, because:

> [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ util ---
[WARNING] **************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [modernizer-maven-annotations-1.8.0.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] **************************************************************************************************************************************************************

It would be nice to get a release which would contain a Automatic-Module-Name entry, thus other artifacts can properly reference it.

**Comment by gaul** [comment]
Can modernizer provide this metadata while ensuring backward compatibility with Java 6?  If so could you submit a pull request?
